# Generated by Django 3.2.5 on 2021-07-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='user_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
