# Generated by Django 3.2.5 on 2021-07-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210716_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakaoaccounts',
            name='email',
            field=models.EmailField(max_length=128, null=True),
        ),
    ]
