# Generated by Django 3.2.5 on 2021-07-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_kakaoaccounts_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KakaoAccounts',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(max_length=128, null=True),
        ),
    ]
